### ISSUE TITLE
The link on github is not working

### ISSUE THREAD

**Issue by muhammederdinc** [csstools/postcss-nesting#100]
![image](https://user-images.githubusercontent.com/33763365/144654271-1261dc7e-ef89-49aa-bf19-f1c65616409a.png)

**Comment by romainmenke** [comment]
@muhammederdinc Thank you for reporting this.

This entire repo will be archived soon as a bunch of plugins are moving to a mono repo : https://github.com/csstools/postcss-plugins

Did you have any specific questions or issues to which you did not find the answer in the readme? Then we can update where needed.

**Comment by muhammederdinc** [comment]
There was no question that I could not find the answer to in readme, I wanted to report when the link did not work :)
