### ISSUE TITLE
Migrate to Postcss 8 API

### ISSUE THREAD

**Issue by bcomnes** [csstools/postcss-nesting#70]
Looks like postcss 7 plugins are working again with 8, but its still recommended to port over to the new PCSS 8 api:

https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by DanielSwensson** [comment]
PR up https://github.com/jonathantneal/postcss-nesting/pull/72

**Comment by JohnAlbin** [comment]
It looks like the current `main` branch needs more updates to be fully PostCSS 8 compliant.

"Step 3: Take the most out of the new API" of the [PostCSS plugin migration guide](https://evilmartians.com/chronicles/postcss-8-plugin-migration) says:

> PostCSS 8 does a single CSS tree scan. Multiple plugins can leverage the same scan for better performance.
>
> To use the single scan you need to remove root.walk* calls and move the code to Declaration(), Rule(), AtRule() or Comment() methods in a plugin’s object:
> ```diff
> module.exports = {
>     postcssPlugin: 'postcss-dark-theme-class',
> -   Once (root) {
> -     root.walkAtRules(atRule => {
> -       // Slow
> -     })
> -   }
> +   AtRule (atRule) {
> +     // Faster
> +   }
>   }
>   module.exports.postcss = true
> ```

postcss-nesting still has:
```js
const postcssNesting = () => {
	return {
		postcssPlugin: 'postcss-nesting',
		Once(root) {
			walk(root);
		}
	}
}
```

I'm experiencing a bug on the latest main branch where CSS added from a previous plugin in the postcss config isn't processed by the later-defined postcss-nesting and I suspect (but don't know) that this might be the reason.

**Comment by bcomnes** [comment]
Looks like jn got a start on it over here: https://github.com/csstools/postcss-nesting/pull/75

Go Jonathan Go!

**Comment by jonathantneal** [comment]
Done in https://github.com/csstools/postcss-nesting/commit/64ba9ac4a56e353b1685adb91cf0a24b425183cc
