### ISSUE TITLE
Missing source maps

### ISSUE THREAD

**Issue by msherringtonmerkle** [csstools/postcss-nesting#71]
Postcss as a dependency of react-dev-utils, itself a dependency of storybook. Just started seeing these warnings...

`Could not read source map for file:///node_modules/postcss-custom-media/index.cjs.js: ENOENT: no such file or directory, open '/node_modules/postcss-custom-media/index.cjs.js.map'`
`Could not read source map for file:///node_modules/postcss-nesting/index.cjs.js: ENOENT: no such file or directory, open '/node_modules/postcss-nesting/index.cjs.js.map'`

All packages are up to date. Warnings persist.

Not sure how to proceed so any help is appreciated, thanks.

**Comment by Semigradsky** [comment]
Which version of PostCSS you has?

**Comment by jonathantneal** [comment]
The v8 releases include source maps. 😄
