### ISSUE TITLE
Throw error on invalid code

### ISSUE THREAD

**Issue by JohnBabenko** [csstools/postcss-nesting#77]
Hello! In the documentation, I did not find how to throw an error if the code is not valid.

Example, there is no ampersand near the button tag:
```
.wrapper {
  button {
    display: flex;
  }
}
```

But package still build invalid code :(
How about implementing this functionality?

**Comment by jonathantneal** [comment]
This plugin won’t throw on that code, and will instead ignore it. This is because some authors may include other plugins that accept the syntax. If linting is desired, use a [stylelint plugin](https://stylelint.io).
