### ISSUE TITLE
v8.0.0 tag does not exist on Github

### ISSUE THREAD

**Issue by gabrielizaias** [csstools/postcss-nesting#79]
We can see the PR landed (#75), and [npmjs.com show the latest version as `v8.0.0`](https://www.npmjs.com/package/postcss-nesting), but the tag does not exist on Github: https://github.com/csstools/postcss-nesting/tags

Perhaps it was not pushed?

**Comment by jonathantneal** [comment]
Version 8 has now been tagged on GitHub, as well as v8.0.1, which resolves an issue in CommonJS environments.

https://github.com/csstools/postcss-nesting/releases/tag/8.0.0
https://github.com/csstools/postcss-nesting/releases/tag/8.0.1
