### ISSUE TITLE
postcss-nesting 8.0.0/9.0.0 incompatible with Node 17+

### ISSUE THREAD

**Issue by onlime** [csstools/postcss-nesting#87]
In postcss-nesting 8.0.0 (see https://github.com/csstools/postcss-nesting/compare/7.0.0...8.0.0), you have limited compatibility to > Node 16 by this change in `package.json`:

```diff
  "engines": {
-    "node": ">=6.0.0"
+    "node": "12 - 16"
  },
```

so we're no longer able to install your package under Node 17:

```bash
$ yarn add --dev postcss-nesting
yarn add v1.22.17
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error postcss-nesting@9.0.0: The engine "node" is incompatible with this module. Expected version "12 - 16". Got "17.0.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

$ node --version
v17.0.1
```

While installing 7.0.0 works fine under Node 17:

```bash
$ yarn add --dev postcss-nesting@7.0.0
```

Can you please fix this for latest 9.x and maybe also backport to a 8.x release (as other important packages like [@nuxtjs/tailwindcss](https://github.com/nuxt-community/tailwindcss-module) have `postcss-nesting@8.0.1` as dev dependency). Thanks!

Cheers, Philip

**Comment by onlime** [comment]
Thanks @jonathantneal for fixing this in 9.0.1

I have now also reported this on https://github.com/nuxt-community/tailwindcss-module/issues/394 so that they upgrade their postcss-nesting dependency.

**Comment by onlime** [comment]
@jonathantneal please publish 9.0.1 on [npm](https://www.npmjs.com/package/postcss-nesting), so that other projects can use it, e.g. nuxt-community/tailwindcss-module#394

**Comment by Antonio-Laguna** [comment]
@onlime that version was broken. We're going to release a new version (10.0.0) hopefully today which will drop support for PostCSS7 and fix this.
