### ISSUE TITLE
postcss-nesting does not work with latest node version (v17.0.0.1 time of writing)

### ISSUE THREAD

**Issue by michahell** [csstools/postcss-nesting#99]
Maybe this was intended, given the descriptive error in this issue:
https://github.com/nuxt/create-nuxt-app/issues/892

In the create-nuxt-app repository

**Comment by Antonio-Laguna** [comment]
@michahell I think you're using an old version of the package since we're on 10.0.1 and that error looks like 8.0.1

**Comment by romainmenke** [comment]
This has been resolved in one of the previous releases.
Thank you for reporting this!
